[build]
  base = "project"
  publish = "dist"
  command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"